import { mkdir, readdir, unlink } from "node:fs/promises";
import { join } from "node:path";
const ROOT = process.cwd();
const DATA = join(ROOT, "src/data/products.json");
const OUT = join(ROOT, "public/products/real");
const CHECKPOINT = join(ROOT, "research/product-image-refresh.json");
const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/128 Safari/537.36";
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const bad = (url: string) => { try { const u = new URL(url); const h = u.hostname.toLowerCase(); const p = u.pathname.toLowerCase(); return u.protocol !== "https:" || h.includes("youtube") || h.includes("ytimg") || h.includes("maps.google") || h.includes("wikipedia") && p.includes("map") || /\.(svg|gif|mp4|webm|mov|avi)(\?|$)/i.test(p) || /(^|\/)(logo|favicon|sprite|mapa)([-_.\/]|$)/i.test(p); } catch { return true; } };
const ext = (type: string, url: string, b: Uint8Array) => { const t = type.split(";", 1)[0].toLowerCase(); if (t.includes("jpeg")) return ".jpg"; if (t.includes("png")) return ".png"; if (t.includes("webp")) return ".webp"; if (t.includes("avif")) return ".avif"; if (b[0] === 0xff && b[1] === 0xd8) return ".jpg"; if (b[0] === 0x89 && b[1] === 0x50) return ".png"; if (b[0] === 0x52 && b[1] === 0x49 && b[2] === 0x46 && b[3] === 0x46) return ".webp"; return new URL(url).pathname.match(/\.(jpg|jpeg|png|webp|avif)$/i)?.[0].replace("jpeg", "jpg") || ".jpg"; };
async function getCandidates(q: string) { const r = await fetch(`https://www.bing.com/images/search?q=${encodeURIComponent(q)}&qft=+filterui:photo-photo`, { headers: { "user-agent": UA, accept: "text/html" }, signal: AbortSignal.timeout(20000) }); if (!r.ok) throw new Error(`HTTP ${r.status}`); const text = (await r.text()).replaceAll("&quot;", "\"").replaceAll("&#34;", "\"").replaceAll("&amp;", "&"); const seen = new Set<string>(); const out: string[] = []; for (const part of text.split("\"murl\"").slice(1)) { const start = part.indexOf("\""); const end = part.indexOf("\"", start + 1); if (start < 0 || end < 0) continue; const u = part.slice(start + 1, end).replaceAll("\\/", "/"); if (!seen.has(u) && !bad(u)) { seen.add(u); out.push(u); } } return out.slice(0, 60); }
async function download(url: string, slug: string) { try { const r = await fetch(url, { headers: { "user-agent": UA, accept: "image/avif,image/webp,image/apng,image/*,*/*;q=0.8", referer: "https://www.bing.com/" }, signal: AbortSignal.timeout(15000) }); if (!r.ok) return null; const b = new Uint8Array(await r.arrayBuffer()); const type = r.headers.get("content-type") || ""; const isImage = type.toLowerCase().startsWith("image/") || b[0] === 0xff && b[1] === 0xd8 || b[0] === 0x89 && b[1] === 0x50 || b[0] === 0x52 && b[1] === 0x49 && b[2] === 0x46 && b[3] === 0x46; if (b.length < 1200 || b.length > 8 * 1024 * 1024 || !isImage) return null; const path = join(OUT, slug + ext(type, url, b)); await Bun.write(path, b); for (const f of await readdir(OUT)) if (f.startsWith(slug + ".") && f !== path.split("/").pop()) await unlink(join(OUT, f)).catch(() => {}); return `/products/real/${path.split("/").pop()}`; } catch { return null; } }
const products: any[] = JSON.parse(await Bun.file(DATA).text()); const state: any = JSON.parse(await Bun.file(CHECKPOINT).text()); const failed = new Set(state.results.filter((x: any) => x.source === "existing-retained").map((x: any) => x.id)); await mkdir(OUT, { recursive: true }); let replaced = 0; let attempted = 0; for (const p of products) { if (!failed.has(p.id)) continue; attempted++; const queries = [`${p.name} producto`, `${p.name} product`, `${p.name} photo`]; let image: string | null = null; let sourceUrl = ""; try { for (const q of queries) { const candidates = await getCandidates(q); for (const url of candidates) { image = await download(url, p.slug); if (image) { sourceUrl = url; break; } await sleep(70); } if (image) break; } } catch {} if (image) { p.image = image; replaced++; const row = state.results.find((x: any) => x.id === p.id); if (row) { row.image = image; row.source = "bing-fallback"; row.sourceUrl = sourceUrl; } } console.log(`${attempted}/${failed.size} ${image ? "replaced" : "failed"} ${p.name}`); await sleep(350); } state.processed = products.length; state.counts.downloaded += replaced; state.counts.bing += replaced; state.counts.failed -= replaced; state.counts.matched += replaced; await Bun.write(DATA, JSON.stringify(products, null, 2) + "\n"); await Bun.write(CHECKPOINT, JSON.stringify(state, null, 2) + "\n"); console.log(JSON.stringify({ attempted, replaced, failed: failed.size - replaced, total: products.length }));
